/**
 * IMPORT AI-GENERATED QUESTIONS SCRIPT
 *
 * This script imports questions generated by AI (ChatGPT/Claude) into the database.
 * It reads JSON files from the ai-questions/ folder and inserts them into MongoDB.
 *
 * USAGE:
 * ts-node src/scripts/import-ai-questions.ts [file_path]
 *
 * EXAMPLES:
 * ts-node src/scripts/import-ai-questions.ts                                    # Import all files from ai-questions/
 * ts-node src/scripts/import-ai-questions.ts ai-questions-new/module_3_questions.json   # Import specific file
 *
 * REQUIREMENTS:
 * - JSON files must be in /ai-questions/ folder (or specify path)
 * - Files should be named: module_0_questions.json, module_1_questions.json, etc.
 * - Each file should contain an array of question objects
 */

import fs from 'fs';
import path from 'path';
import database from '../config/database.config';
import { QuestionModel } from '../models/question.model';
import { QuestionStatus } from '../types';
import logger from '../utils/logger.util';

interface QuestionImportStats {
  totalFiles: number;
  successfulImports: number;
  failedImports: number;
  totalQuestions: number;
  duplicatesSkipped: number;
}

/**
 * Validate question data structure
 */
function validateQuestion(question: any, moduleId: number): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  // Required fields
  if (!question.question_code) errors.push('Missing question_code');
  if (question.module_id !== moduleId) errors.push(`module_id mismatch: expected ${moduleId}, got ${question.module_id}`);
  if (!question.micro_skill_id) errors.push('Missing micro_skill_id');
  if (!question.question_data) errors.push('Missing question_data');
  if (!question.metadata) errors.push('Missing metadata');

  // Question data validation
  if (question.question_data) {
    if (!question.question_data.text) errors.push('Missing question text');
    if (!question.question_data.type) errors.push('Missing question type');
    if (!question.question_data.correct_answer) errors.push('Missing correct answer');
    if (!Array.isArray(question.question_data.solution_steps) || question.question_data.solution_steps.length === 0) {
      errors.push('Missing or empty solution_steps');
    }
    if (!Array.isArray(question.question_data.hints) || question.question_data.hints.length === 0) {
      errors.push('Missing or empty hints');
    }
  }

  // Metadata validation
  if (question.metadata) {
    if (!question.metadata.difficulty_level || question.metadata.difficulty_level < 1 || question.metadata.difficulty_level > 10) {
      errors.push('Invalid difficulty_level (must be 1-10)');
    }
    if (!question.metadata.expected_time_seconds) errors.push('Missing expected_time_seconds');
    if (!question.metadata.points) errors.push('Missing points');
    if (!Array.isArray(question.metadata.tags)) errors.push('Missing or invalid tags array');
  }

  return {
    valid: errors.length === 0,
    errors
  };
}

/**
 * Import questions from a single JSON file
 */
async function importModuleQuestions(filepath: string, moduleId: number): Promise<{
  imported: number;
  skipped: number;
  failed: number;
}> {
  let imported = 0;
  let skipped = 0;
  let failed = 0;

  try {
    // Read JSON file
    const fileContent = fs.readFileSync(filepath, 'utf-8');
    let questions: any[];

    try {
      const parsed = JSON.parse(fileContent);
      // Handle both array format and object with questions property
      questions = Array.isArray(parsed) ? parsed : (parsed.questions || []);
    } catch (parseError) {
      logger.error(`Invalid JSON in file ${filepath}:`, parseError);
      throw new Error('Invalid JSON format');
    }

    if (!Array.isArray(questions) || questions.length === 0) {
      logger.warn(`No questions found in ${filepath}`);
      return { imported, skipped, failed };
    }

    logger.info(`Found ${questions.length} questions in file`);

    // Process each question
    for (const questionData of questions) {
      try {
        // Validate question
        const validation = validateQuestion(questionData, moduleId);
        if (!validation.valid) {
          logger.warn(`Skipping invalid question ${questionData.question_code}:`);
          validation.errors.forEach(err => logger.warn(`  - ${err}`));
          failed++;
          continue;
        }

        // Check if question already exists
        const existing = await QuestionModel.findOne({
          question_code: questionData.question_code
        });

        if (existing) {
          logger.debug(`Question ${questionData.question_code} already exists, skipping`);
          skipped++;
          continue;
        }

        // Set default status if not provided
        if (!questionData.status) {
          questionData.status = QuestionStatus.ACTIVE;
        }

        // Initialize performance metrics if not provided
        if (!questionData.performance) {
          questionData.performance = {
            total_attempts: 0,
            success_rate: 0,
            avg_hints_used: 0,
            abandon_rate: 0,
          };
        }

        // Create and save question
        const question = new QuestionModel(questionData);
        await question.save();

        imported++;
        logger.debug(`✓ Imported: ${questionData.question_code}`);

      } catch (error: any) {
        logger.error(`Failed to import question ${questionData.question_code}:`);
        logger.error(`  Error: ${error.message || JSON.stringify(error)}`);
        if (error.stack) {
          logger.debug(`  Stack: ${error.stack}`);
        }
        failed++;
      }
    }

  } catch (error: any) {
    logger.error(`Error processing file ${filepath}:`, error);
    throw error;
  }

  return { imported, skipped, failed };
}

/**
 * Main import function
 */
async function importAllQuestions() {
  // Check for command-line argument
  const specificFile = process.argv[2];
  const questionsDir = path.join(process.cwd(), 'ai-questions');

  const stats: QuestionImportStats = {
    totalFiles: 0,
    successfulImports: 0,
    failedImports: 0,
    totalQuestions: 0,
    duplicatesSkipped: 0,
  };

  try {
    // Connect to database
    logger.info('Connecting to database...');
    await database.connect();
    logger.info('✅ Database connected');

    // If specific file provided, import only that file
    if (specificFile) {
      const filepath = path.join(process.cwd(), specificFile);

      if (!fs.existsSync(filepath)) {
        logger.error(`File not found: ${filepath}`);
        process.exit(1);
      }

      // Extract module ID from filename
      const filename = path.basename(filepath);
      const match = filename.match(/module_(\d+)_questions\.json/);

      if (!match) {
        logger.error(`Invalid filename format: ${filename}`);
        logger.info('Expected format: module_X_questions.json');
        process.exit(1);
      }

      const moduleId = parseInt(match[1], 10);

      logger.info(`\n${'='.repeat(60)}`);
      logger.info(`📝 Importing specific file: ${filename}`);
      logger.info(`📦 Module ${moduleId}`);
      logger.info('='.repeat(60));

      const result = await importModuleQuestions(filepath, moduleId);

      logger.info(`\n✅ Import complete:`);
      logger.info(`   Imported: ${result.imported}`);
      logger.info(`   Skipped (duplicates): ${result.skipped}`);
      logger.info(`   Failed: ${result.failed}`);

      // Update stats
      stats.totalFiles = 1;
      stats.successfulImports = result.imported;
      stats.duplicatesSkipped = result.skipped;
      stats.failedImports = result.failed;
      stats.totalQuestions = result.imported;

      // Verify total count in database
      const totalInDb = await QuestionModel.countDocuments();
      logger.info(`\n✅ Database verification: ${totalInDb} total questions`);

      return;
    }

    // Otherwise, import all files from ai-questions directory
    // Check if directory exists
    if (!fs.existsSync(questionsDir)) {
      logger.error(`Directory not found: ${questionsDir}`);
      logger.info('Please create the ai-questions/ folder and add your JSON files');
      process.exit(1);
    }

    // Read all JSON files
    const files = fs.readdirSync(questionsDir)
      .filter(file => file.endsWith('.json') && file.startsWith('module_'))
      .sort(); // Sort to process in order

    if (files.length === 0) {
      logger.warn('No module JSON files found in ai-questions/ folder');
      logger.info('Expected files: module_0_questions.json, module_1_questions.json, etc.');
      process.exit(0);
    }

    logger.info(`\n📁 Found ${files.length} module files\n`);

    // Process each file
    for (const file of files) {
      // Extract module ID from filename (e.g., module_0_questions.json)
      const match = file.match(/module_(\d+)_questions\.json/);
      if (!match) {
        logger.warn(`Skipping file with invalid name: ${file}`);
        continue;
      }

      const moduleId = parseInt(match[1], 10);
      const filepath = path.join(questionsDir, file);

      stats.totalFiles++;

      logger.info(`\n${'='.repeat(60)}`);
      logger.info(`📝 Processing Module ${moduleId}: ${file}`);
      logger.info('='.repeat(60));

      try {
        const result = await importModuleQuestions(filepath, moduleId);

        stats.successfulImports += result.imported;
        stats.duplicatesSkipped += result.skipped;
        stats.failedImports += result.failed;
        stats.totalQuestions += result.imported;

        logger.info(`\n✅ Module ${moduleId} complete:`);
        logger.info(`   Imported: ${result.imported}`);
        logger.info(`   Skipped (duplicates): ${result.skipped}`);
        logger.info(`   Failed: ${result.failed}`);

      } catch (error: any) {
        logger.error(`❌ Failed to process module ${moduleId}:`, error.message);
      }
    }

    // Print final summary
    logger.info(`\n${'═'.repeat(60)}`);
    logger.info('📊 IMPORT SUMMARY');
    logger.info('═'.repeat(60));
    logger.info(`Files processed: ${stats.totalFiles}`);
    logger.info(`Questions imported: ${stats.successfulImports}`);
    logger.info(`Duplicates skipped: ${stats.duplicatesSkipped}`);
    logger.info(`Failed imports: ${stats.failedImports}`);
    logger.info(`Total questions in DB: ${stats.totalQuestions}`);
    logger.info('═'.repeat(60));

    // Verify total count in database
    const totalInDb = await QuestionModel.countDocuments();
    logger.info(`\n✅ Database verification: ${totalInDb} total questions`);

  } catch (error: any) {
    logger.error('Import failed:', error);
    process.exit(1);
  } finally {
    // Disconnect from database
    await database.disconnect();
    logger.info('\n👋 Database disconnected');
  }
}

// Run the script
if (require.main === module) {
  importAllQuestions()
    .then(() => {
      logger.info('\n✅ Import completed successfully!');
      process.exit(0);
    })
    .catch((error) => {
      logger.error('Import failed:', error);
      process.exit(1);
    });
}

export { importAllQuestions };
